// Generated by gencpp from file yolo_onnx_ros/ObjectDetectionResponse.msg
// DO NOT EDIT!


#ifndef YOLO_ONNX_ROS_MESSAGE_OBJECTDETECTIONRESPONSE_H
#define YOLO_ONNX_ROS_MESSAGE_OBJECTDETECTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_onnx_ros
{
template <class ContainerAllocator>
struct ObjectDetectionResponse_
{
  typedef ObjectDetectionResponse_<ContainerAllocator> Type;

  ObjectDetectionResponse_()
    : success(false)
    , message()
    , detected_classes()
    , confidences()
    , bboxes()
    , class_names()
    , class_counts()  {
    }
  ObjectDetectionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , detected_classes(_alloc)
    , confidences(_alloc)
    , bboxes(_alloc)
    , class_names(_alloc)
    , class_counts(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _detected_classes_type;
  _detected_classes_type detected_classes;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _confidences_type;
  _confidences_type confidences;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _bboxes_type;
  _bboxes_type bboxes;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _class_names_type;
  _class_names_type class_names;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _class_counts_type;
  _class_counts_type class_counts;





  typedef boost::shared_ptr< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDetectionResponse_

typedef ::yolo_onnx_ros::ObjectDetectionResponse_<std::allocator<void> > ObjectDetectionResponse;

typedef boost::shared_ptr< ::yolo_onnx_ros::ObjectDetectionResponse > ObjectDetectionResponsePtr;
typedef boost::shared_ptr< ::yolo_onnx_ros::ObjectDetectionResponse const> ObjectDetectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator1> & lhs, const ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.detected_classes == rhs.detected_classes &&
    lhs.confidences == rhs.confidences &&
    lhs.bboxes == rhs.bboxes &&
    lhs.class_names == rhs.class_names &&
    lhs.class_counts == rhs.class_counts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator1> & lhs, const ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_onnx_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "489bc24994a8b7435ec34005c4c3ad9a";
  }

  static const char* value(const ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x489bc24994a8b743ULL;
  static const uint64_t static_value2 = 0x5ec34005c4c3ad9aULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_onnx_ros/ObjectDetectionResponse";
  }

  static const char* value(const ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"string[] detected_classes\n"
"float32[] confidences\n"
"int32[] bboxes\n"
"string[] class_names\n"
"int32[] class_counts\n"
;
  }

  static const char* value(const ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.detected_classes);
      stream.next(m.confidences);
      stream.next(m.bboxes);
      stream.next(m.class_names);
      stream.next(m.class_counts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDetectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_onnx_ros::ObjectDetectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "detected_classes[]" << std::endl;
    for (size_t i = 0; i < v.detected_classes.size(); ++i)
    {
      s << indent << "  detected_classes[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.detected_classes[i]);
    }
    s << indent << "confidences[]" << std::endl;
    for (size_t i = 0; i < v.confidences.size(); ++i)
    {
      s << indent << "  confidences[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.confidences[i]);
    }
    s << indent << "bboxes[]" << std::endl;
    for (size_t i = 0; i < v.bboxes.size(); ++i)
    {
      s << indent << "  bboxes[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.bboxes[i]);
    }
    s << indent << "class_names[]" << std::endl;
    for (size_t i = 0; i < v.class_names.size(); ++i)
    {
      s << indent << "  class_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.class_names[i]);
    }
    s << indent << "class_counts[]" << std::endl;
    for (size_t i = 0; i < v.class_counts.size(); ++i)
    {
      s << indent << "  class_counts[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.class_counts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_ONNX_ROS_MESSAGE_OBJECTDETECTIONRESPONSE_H
