// Generated by gencpp from file yolo_onnx_ros/ObjectDetection.msg
// DO NOT EDIT!


#ifndef YOLO_ONNX_ROS_MESSAGE_OBJECTDETECTION_H
#define YOLO_ONNX_ROS_MESSAGE_OBJECTDETECTION_H

#include <ros/service_traits.h>


#include <yolo_onnx_ros/ObjectDetectionRequest.h>
#include <yolo_onnx_ros/ObjectDetectionResponse.h>


namespace yolo_onnx_ros
{

struct ObjectDetection
{

typedef ObjectDetectionRequest Request;
typedef ObjectDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ObjectDetection
} // namespace yolo_onnx_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yolo_onnx_ros::ObjectDetection > {
  static const char* value()
  {
    return "72cb1f993fa530515d2ffbaf79b1be27";
  }

  static const char* value(const ::yolo_onnx_ros::ObjectDetection&) { return value(); }
};

template<>
struct DataType< ::yolo_onnx_ros::ObjectDetection > {
  static const char* value()
  {
    return "yolo_onnx_ros/ObjectDetection";
  }

  static const char* value(const ::yolo_onnx_ros::ObjectDetection&) { return value(); }
};


// service_traits::MD5Sum< ::yolo_onnx_ros::ObjectDetectionRequest> should match
// service_traits::MD5Sum< ::yolo_onnx_ros::ObjectDetection >
template<>
struct MD5Sum< ::yolo_onnx_ros::ObjectDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yolo_onnx_ros::ObjectDetection >::value();
  }
  static const char* value(const ::yolo_onnx_ros::ObjectDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yolo_onnx_ros::ObjectDetectionRequest> should match
// service_traits::DataType< ::yolo_onnx_ros::ObjectDetection >
template<>
struct DataType< ::yolo_onnx_ros::ObjectDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::yolo_onnx_ros::ObjectDetection >::value();
  }
  static const char* value(const ::yolo_onnx_ros::ObjectDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yolo_onnx_ros::ObjectDetectionResponse> should match
// service_traits::MD5Sum< ::yolo_onnx_ros::ObjectDetection >
template<>
struct MD5Sum< ::yolo_onnx_ros::ObjectDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yolo_onnx_ros::ObjectDetection >::value();
  }
  static const char* value(const ::yolo_onnx_ros::ObjectDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yolo_onnx_ros::ObjectDetectionResponse> should match
// service_traits::DataType< ::yolo_onnx_ros::ObjectDetection >
template<>
struct DataType< ::yolo_onnx_ros::ObjectDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::yolo_onnx_ros::ObjectDetection >::value();
  }
  static const char* value(const ::yolo_onnx_ros::ObjectDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOLO_ONNX_ROS_MESSAGE_OBJECTDETECTION_H
