// Generated by gencpp from file text_recognition/RecognizeTextResponse.msg
// DO NOT EDIT!


#ifndef TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXTRESPONSE_H
#define TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace text_recognition
{
template <class ContainerAllocator>
struct RecognizeTextResponse_
{
  typedef RecognizeTextResponse_<ContainerAllocator> Type;

  RecognizeTextResponse_()
    : text()
    , confidence(0.0)
    , status()  {
    }
  RecognizeTextResponse_(const ContainerAllocator& _alloc)
    : text(_alloc)
    , confidence(0.0)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RecognizeTextResponse_

typedef ::text_recognition::RecognizeTextResponse_<std::allocator<void> > RecognizeTextResponse;

typedef boost::shared_ptr< ::text_recognition::RecognizeTextResponse > RecognizeTextResponsePtr;
typedef boost::shared_ptr< ::text_recognition::RecognizeTextResponse const> RecognizeTextResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::text_recognition::RecognizeTextResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::text_recognition::RecognizeTextResponse_<ContainerAllocator1> & lhs, const ::text_recognition::RecognizeTextResponse_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text &&
    lhs.confidence == rhs.confidence &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::text_recognition::RecognizeTextResponse_<ContainerAllocator1> & lhs, const ::text_recognition::RecognizeTextResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace text_recognition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ef6ea0323417c9ea59ffa9676481cc1";
  }

  static const char* value(const ::text_recognition::RecognizeTextResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ef6ea0323417c9eULL;
  static const uint64_t static_value2 = 0xa59ffa9676481cc1ULL;
};

template<class ContainerAllocator>
struct DataType< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "text_recognition/RecognizeTextResponse";
  }

  static const char* value(const ::text_recognition::RecognizeTextResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应：返回识别结果\n"
"string text          # 识别的文字\n"
"float32 confidence   # 置信度\n"
"string status        # 状态信息\n"
"\n"
;
  }

  static const char* value(const ::text_recognition::RecognizeTextResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
      stream.next(m.confidence);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognizeTextResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::text_recognition::RecognizeTextResponse_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXTRESPONSE_H
