// Generated by gencpp from file text_recognition/RecognizeTextRequest.msg
// DO NOT EDIT!


#ifndef TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXTREQUEST_H
#define TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace text_recognition
{
template <class ContainerAllocator>
struct RecognizeTextRequest_
{
  typedef RecognizeTextRequest_<ContainerAllocator> Type;

  RecognizeTextRequest_()
    : image_path()  {
    }
  RecognizeTextRequest_(const ContainerAllocator& _alloc)
    : image_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _image_path_type;
  _image_path_type image_path;





  typedef boost::shared_ptr< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RecognizeTextRequest_

typedef ::text_recognition::RecognizeTextRequest_<std::allocator<void> > RecognizeTextRequest;

typedef boost::shared_ptr< ::text_recognition::RecognizeTextRequest > RecognizeTextRequestPtr;
typedef boost::shared_ptr< ::text_recognition::RecognizeTextRequest const> RecognizeTextRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::text_recognition::RecognizeTextRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::text_recognition::RecognizeTextRequest_<ContainerAllocator1> & lhs, const ::text_recognition::RecognizeTextRequest_<ContainerAllocator2> & rhs)
{
  return lhs.image_path == rhs.image_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::text_recognition::RecognizeTextRequest_<ContainerAllocator1> & lhs, const ::text_recognition::RecognizeTextRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace text_recognition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65568c775bfbc96c6265c3d13d7e1a07";
  }

  static const char* value(const ::text_recognition::RecognizeTextRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65568c775bfbc96cULL;
  static const uint64_t static_value2 = 0x6265c3d13d7e1a07ULL;
};

template<class ContainerAllocator>
struct DataType< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "text_recognition/RecognizeTextRequest";
  }

  static const char* value(const ::text_recognition::RecognizeTextRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求：图片路径\n"
"string image_path\n"
"\n"
;
  }

  static const char* value(const ::text_recognition::RecognizeTextRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognizeTextRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::text_recognition::RecognizeTextRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::text_recognition::RecognizeTextRequest_<ContainerAllocator>& v)
  {
    s << indent << "image_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXTREQUEST_H
