// Generated by gencpp from file text_recognition/RecognizeTextResponse.msg
// DO NOT EDIT!


#ifndef TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXTRESPONSE_H
#define TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace text_recognition
{
template <class ContainerAllocator>
struct RecognizeTextResponse_
{
  typedef RecognizeTextResponse_<ContainerAllocator> Type;

  RecognizeTextResponse_()
    : lab_open(false)
    , wait_seconds(0)
    , speech_text()  {
    }
  RecognizeTextResponse_(const ContainerAllocator& _alloc)
    : lab_open(false)
    , wait_seconds(0)
    , speech_text(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _lab_open_type;
  _lab_open_type lab_open;

   typedef int32_t _wait_seconds_type;
  _wait_seconds_type wait_seconds;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _speech_text_type;
  _speech_text_type speech_text;





  typedef boost::shared_ptr< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RecognizeTextResponse_

typedef ::text_recognition::RecognizeTextResponse_<std::allocator<void> > RecognizeTextResponse;

typedef boost::shared_ptr< ::text_recognition::RecognizeTextResponse > RecognizeTextResponsePtr;
typedef boost::shared_ptr< ::text_recognition::RecognizeTextResponse const> RecognizeTextResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::text_recognition::RecognizeTextResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::text_recognition::RecognizeTextResponse_<ContainerAllocator1> & lhs, const ::text_recognition::RecognizeTextResponse_<ContainerAllocator2> & rhs)
{
  return lhs.lab_open == rhs.lab_open &&
    lhs.wait_seconds == rhs.wait_seconds &&
    lhs.speech_text == rhs.speech_text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::text_recognition::RecognizeTextResponse_<ContainerAllocator1> & lhs, const ::text_recognition::RecognizeTextResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace text_recognition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61a7d919646176c35855862f25c89e0a";
  }

  static const char* value(const ::text_recognition::RecognizeTextResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61a7d919646176c3ULL;
  static const uint64_t static_value2 = 0x5855862f25c89e0aULL;
};

template<class ContainerAllocator>
struct DataType< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "text_recognition/RecognizeTextResponse";
  }

  static const char* value(const ::text_recognition::RecognizeTextResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应\n"
"bool lab_open        # 是否空闲（可扩展）\n"
"int32 wait_seconds   # 等待秒数（可扩展）\n"
"string speech_text   # 识别出的文字\n"
"\n"
;
  }

  static const char* value(const ::text_recognition::RecognizeTextResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lab_open);
      stream.next(m.wait_seconds);
      stream.next(m.speech_text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognizeTextResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::text_recognition::RecognizeTextResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::text_recognition::RecognizeTextResponse_<ContainerAllocator>& v)
  {
    s << indent << "lab_open: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lab_open);
    s << indent << "wait_seconds: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wait_seconds);
    s << indent << "speech_text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.speech_text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXTRESPONSE_H
