// Generated by gencpp from file text_recognition/RecognizeText.msg
// DO NOT EDIT!


#ifndef TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXT_H
#define TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXT_H

#include <ros/service_traits.h>


#include <text_recognition/RecognizeTextRequest.h>
#include <text_recognition/RecognizeTextResponse.h>


namespace text_recognition
{

struct RecognizeText
{

typedef RecognizeTextRequest Request;
typedef RecognizeTextResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RecognizeText
} // namespace text_recognition


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::text_recognition::RecognizeText > {
  static const char* value()
  {
    return "992db631aebc62bb18995fe2bf59be7e";
  }

  static const char* value(const ::text_recognition::RecognizeText&) { return value(); }
};

template<>
struct DataType< ::text_recognition::RecognizeText > {
  static const char* value()
  {
    return "text_recognition/RecognizeText";
  }

  static const char* value(const ::text_recognition::RecognizeText&) { return value(); }
};


// service_traits::MD5Sum< ::text_recognition::RecognizeTextRequest> should match
// service_traits::MD5Sum< ::text_recognition::RecognizeText >
template<>
struct MD5Sum< ::text_recognition::RecognizeTextRequest>
{
  static const char* value()
  {
    return MD5Sum< ::text_recognition::RecognizeText >::value();
  }
  static const char* value(const ::text_recognition::RecognizeTextRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_recognition::RecognizeTextRequest> should match
// service_traits::DataType< ::text_recognition::RecognizeText >
template<>
struct DataType< ::text_recognition::RecognizeTextRequest>
{
  static const char* value()
  {
    return DataType< ::text_recognition::RecognizeText >::value();
  }
  static const char* value(const ::text_recognition::RecognizeTextRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::text_recognition::RecognizeTextResponse> should match
// service_traits::MD5Sum< ::text_recognition::RecognizeText >
template<>
struct MD5Sum< ::text_recognition::RecognizeTextResponse>
{
  static const char* value()
  {
    return MD5Sum< ::text_recognition::RecognizeText >::value();
  }
  static const char* value(const ::text_recognition::RecognizeTextResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::text_recognition::RecognizeTextResponse> should match
// service_traits::DataType< ::text_recognition::RecognizeText >
template<>
struct DataType< ::text_recognition::RecognizeTextResponse>
{
  static const char* value()
  {
    return DataType< ::text_recognition::RecognizeText >::value();
  }
  static const char* value(const ::text_recognition::RecognizeTextResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEXT_RECOGNITION_MESSAGE_RECOGNIZETEXT_H
