// Generated by gencpp from file license_plate_ocr/LicensePlateOCRResponse.msg
// DO NOT EDIT!


#ifndef LICENSE_PLATE_OCR_MESSAGE_LICENSEPLATEOCRRESPONSE_H
#define LICENSE_PLATE_OCR_MESSAGE_LICENSEPLATEOCRRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace license_plate_ocr
{
template <class ContainerAllocator>
struct LicensePlateOCRResponse_
{
  typedef LicensePlateOCRResponse_<ContainerAllocator> Type;

  LicensePlateOCRResponse_()
    : plate_texts()
    , confidences()
    , status_message()  {
    }
  LicensePlateOCRResponse_(const ContainerAllocator& _alloc)
    : plate_texts(_alloc)
    , confidences(_alloc)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _plate_texts_type;
  _plate_texts_type plate_texts;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _confidences_type;
  _confidences_type confidences;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LicensePlateOCRResponse_

typedef ::license_plate_ocr::LicensePlateOCRResponse_<std::allocator<void> > LicensePlateOCRResponse;

typedef boost::shared_ptr< ::license_plate_ocr::LicensePlateOCRResponse > LicensePlateOCRResponsePtr;
typedef boost::shared_ptr< ::license_plate_ocr::LicensePlateOCRResponse const> LicensePlateOCRResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator1> & lhs, const ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator2> & rhs)
{
  return lhs.plate_texts == rhs.plate_texts &&
    lhs.confidences == rhs.confidences &&
    lhs.status_message == rhs.status_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator1> & lhs, const ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace license_plate_ocr

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "992dcf1bf25275ccf4fb7dcadfb15de4";
  }

  static const char* value(const ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x992dcf1bf25275ccULL;
  static const uint64_t static_value2 = 0xf4fb7dcadfb15de4ULL;
};

template<class ContainerAllocator>
struct DataType< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "license_plate_ocr/LicensePlateOCRResponse";
  }

  static const char* value(const ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应：返回识别结果\n"
"string[] plate_texts\n"
"float32[] confidences\n"
"string status_message\n"
;
  }

  static const char* value(const ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plate_texts);
      stream.next(m.confidences);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LicensePlateOCRResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::license_plate_ocr::LicensePlateOCRResponse_<ContainerAllocator>& v)
  {
    s << indent << "plate_texts[]" << std::endl;
    for (size_t i = 0; i < v.plate_texts.size(); ++i)
    {
      s << indent << "  plate_texts[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.plate_texts[i]);
    }
    s << indent << "confidences[]" << std::endl;
    for (size_t i = 0; i < v.confidences.size(); ++i)
    {
      s << indent << "  confidences[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.confidences[i]);
    }
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LICENSE_PLATE_OCR_MESSAGE_LICENSEPLATEOCRRESPONSE_H
