// Generated by gencpp from file license_plate_ocr/LicensePlateOCR.msg
// DO NOT EDIT!


#ifndef LICENSE_PLATE_OCR_MESSAGE_LICENSEPLATEOCR_H
#define LICENSE_PLATE_OCR_MESSAGE_LICENSEPLATEOCR_H

#include <ros/service_traits.h>


#include <license_plate_ocr/LicensePlateOCRRequest.h>
#include <license_plate_ocr/LicensePlateOCRResponse.h>


namespace license_plate_ocr
{

struct LicensePlateOCR
{

typedef LicensePlateOCRRequest Request;
typedef LicensePlateOCRResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LicensePlateOCR
} // namespace license_plate_ocr


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::license_plate_ocr::LicensePlateOCR > {
  static const char* value()
  {
    return "bc0aa725c8a3f5abac8f917be5e39777";
  }

  static const char* value(const ::license_plate_ocr::LicensePlateOCR&) { return value(); }
};

template<>
struct DataType< ::license_plate_ocr::LicensePlateOCR > {
  static const char* value()
  {
    return "license_plate_ocr/LicensePlateOCR";
  }

  static const char* value(const ::license_plate_ocr::LicensePlateOCR&) { return value(); }
};


// service_traits::MD5Sum< ::license_plate_ocr::LicensePlateOCRRequest> should match
// service_traits::MD5Sum< ::license_plate_ocr::LicensePlateOCR >
template<>
struct MD5Sum< ::license_plate_ocr::LicensePlateOCRRequest>
{
  static const char* value()
  {
    return MD5Sum< ::license_plate_ocr::LicensePlateOCR >::value();
  }
  static const char* value(const ::license_plate_ocr::LicensePlateOCRRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::license_plate_ocr::LicensePlateOCRRequest> should match
// service_traits::DataType< ::license_plate_ocr::LicensePlateOCR >
template<>
struct DataType< ::license_plate_ocr::LicensePlateOCRRequest>
{
  static const char* value()
  {
    return DataType< ::license_plate_ocr::LicensePlateOCR >::value();
  }
  static const char* value(const ::license_plate_ocr::LicensePlateOCRRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::license_plate_ocr::LicensePlateOCRResponse> should match
// service_traits::MD5Sum< ::license_plate_ocr::LicensePlateOCR >
template<>
struct MD5Sum< ::license_plate_ocr::LicensePlateOCRResponse>
{
  static const char* value()
  {
    return MD5Sum< ::license_plate_ocr::LicensePlateOCR >::value();
  }
  static const char* value(const ::license_plate_ocr::LicensePlateOCRResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::license_plate_ocr::LicensePlateOCRResponse> should match
// service_traits::DataType< ::license_plate_ocr::LicensePlateOCR >
template<>
struct DataType< ::license_plate_ocr::LicensePlateOCRResponse>
{
  static const char* value()
  {
    return DataType< ::license_plate_ocr::LicensePlateOCR >::value();
  }
  static const char* value(const ::license_plate_ocr::LicensePlateOCRResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LICENSE_PLATE_OCR_MESSAGE_LICENSEPLATEOCR_H
